
[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "npm ci",
  "npm run build"
]

[phases.build]
cmds = [
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"

[[static]]
directory = "public/build"
asset_url = "/build"
cache_control = "public, max-age=31536000"

[[static]]
directory = "public/images"
asset_url = "/images"
cache_control = "public, max-age=31536000"
